export default {
  FETCH_DATA: "FETCH_DATA",
  FETCH_DATA_REQUESTED: "FETCH_DATA_REQUESTED",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_FAILED: "FETCH_DATA_FAILED",
  FETCH_VEHICLE: "FETCH_VEHICLE",
  FETCH_VEHICLE_REQUESTED: "FETCH_VEHICLE_REQUESTED",
  FETCH_VEHICLE_SUCCESS: "FETCH_VEHICLE_SUCCESS",
  FETCH_VEHICLE_FAILED: "FETCH_VEHICLE_FAILED",
  UPDATE_VEHICLES: "UPDATE_VEHICLES",
  UPDATE_VEHICLES_REQUESTED: "UPDATE_VEHICLES_REQUESTED",
  UPDATE_VEHICLES_SUCCESS: "UPDATE_VEHICLES_SUCCESS",
  UPDATE_VEHICLES_FAILED: "UPDATE_VEHICLES_FAILED"
};
